# Generated by Django 5.1.3 on 2024-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_is_multiple_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_per_question',
            field=models.PositiveIntegerField(default=60, verbose_name='Время на вопрос (секунды)'),
        ),
    ]
