# Generated by Django 5.1.3 on 2025-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_multiple_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('text_input', 'Ввод текста')], default='single_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
