# Generated by Django 5.1.3 on 2024-11-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_is_multiple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multipliers',
            field=models.JSONField(default={'1': 2.0, '2': 1.7, '3': 1.5, '4': 1.4, '5': 1.2}, verbose_name='Множители'),
        ),
    ]
