# Generated by Django 5.1.3 on 2025-02-14 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_loadingtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=100, verbose_name='Промокод')),
                ('is_given', models.BooleanField(default=False, verbose_name='Выдан ли пользователю')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='quiz.user', verbose_name='Получатель')),
            ],
        ),
    ]
