# Generated by Django 5.1.3 on 2024-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_multipliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multipliers',
            field=models.JSONField(default=dict, verbose_name='Множители'),
        ),
    ]
