# Generated by Django 5.1.3 on 2025-02-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='quiz.promocodes', verbose_name='награда'),
        ),
    ]
