# Generated by Django 5.1.3 on 2024-11-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_question_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_per_question',
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=20, verbose_name='Время на ответ (секунды)'),
        ),
    ]
